### ISSUE TITLE
Incorrectly determines the time in the world on the server

### ISSUE THREAD

**Issue by DarkFenix139** [Arycer/RoseHud#2]
Incorrectly determines the time in the world on the server. While the minimap mod does it right.

https://sun9-37.userapi.com/impg/ieR2EmhH_QQjBm8Ai-kQGRXcXK80t2JWO3w7nw/1Km_rlhUYyk.jpg?size=385x439&quality=96&sign=bbf32596a44a240f650325c49b07ddba&type=album

**Comment by Arycer** [comment]
I think that might be because the minimap displays the Minecraft time in a 24hour-like format, while I just display the time in the 20 minute format (10 minute day, 10 minute night) so that should not be a bug. Anyway, I'll have this in mind for a future update so you can change the format to the 24hour-like format!

**Comment by DarkFenix139** [comment]
Understood. It was unintuitive for me when it showed “7:14”, as if it was morning, although it was already day in the game.
